/*
-- Query: SELECT * FROM homestead.medicamentos
LIMIT 0, 1000

-- Date: 2020-05-19 23:25
*/
INSERT INTO `medicamentos` (`id`,`nombre`,`categoria`,`descripcion`) VALUES (2,'Carbidopa-levodopa','Categoria1','La levodopa, el medicamento más eficaz contra la enfermedad de Parkinson, es una sustancia química natural que ingresa al cerebro y se convierte en dopamina.\r\n\r\nLa levodopa se combina con la carbidopa (Lodosyn), que evita la conversión prematura de la levodopa en dopamina fuera del cerebro. Esto previene o disminuye los efectos secundarios, como las náuseas.\r\n\r\nLos efectos secundarios pueden incluir náuseas o aturdimiento (hipotensión ortostática).\r\n\r\nDespués de algunos años, a medida que la enfermedad avanza, el beneficio de la levodopa puede volverse menos estable, con una tendencia a fluctuar (“deja de tener efecto”).\r\n\r\nAdemás, puedes experimentar movimientos involuntarios (discinesia) después de consumir dosis más altas de levodopa. El médico podría disminuir tu dosis o modificar los horarios de tus dosis para controlar estos efectos.');
INSERT INTO `medicamentos` (`id`,`nombre`,`categoria`,`descripcion`) VALUES (3,'Dopamina','Categoria1','A diferencia de la levodopa, los agonistas de la dopamina no se transforman en dopamina. En cambio, imitan los efectos de la dopamina en el cerebro.\r\n\r\nNo son tan eficaces como la levodopa para tratar los síntomas. Sin embargo, duran más tiempo y pueden usarse con la levodopa para atenuar los efectos a menudo irregulares de la levodopa.\r\n\r\nLos agonistas de la dopamina son el pramipexol (Mirapex), el ropinirol (Requip) y la rotigotina (Neupro, administrada como un parche). La apomorfina (Apokyn) es un agonista de la dopamina inyectable de acción breve que se usa para proporcionar un alivio rápido.\r\n\r\nAlgunos de los efectos secundarios de los agonistas de la dopamina son similares a los efectos secundarios de la carbidopa-levodopa. Pero también pueden incluir alucinaciones, somnolencia y comportamientos compulsivos como hipersexualidad, adicción al juego y exceso de apetito. Si tomas estos medicamentos y te comportas de una manera inusual para ti, consulta con el médico.');
INSERT INTO `medicamentos` (`id`,`nombre`,`categoria`,`descripcion`) VALUES (4,'Amantadina','Categoria2','Los médicos pueden recetar amantadina sola para brindar alivio a corto plazo de los síntomas de la enfermedad de Parkinson leve y en etapa temprana. También puede administrarse junto con el tratamiento de carbidopa-levodopa durante las etapas finales de la enfermedad de Parkinson para controlar los movimientos involuntarios (discinesia) inducidos por la carbidopa-levodopa.\r\n\r\nLos efectos secundarios pueden comprender manchas moradas en la piel, hinchazón de los tobillos o alucinaciones.');
