/*
-- Query: SELECT * FROM homestead.preguntas
LIMIT 0, 1000

-- Date: 2020-05-19 23:23
*/
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (1,NULL,NULL,'1. ALTERACION DEL INTELECTO','0 = Nula \n 1 = Leve, Falta de memoria evidente, con recuerdo parcial de los acontecimientos, sin otras dificultades.  \n 2 = Pérdida moderada de memoria, con desorientación y dificultad moderada para la resolución de problemas más complejos. Alteración funcional discreta, pero evidente en el hogar con necesidad de recordarle ocasionalmente las cosas.  \n 3 = Pérdida grave de memoria con desorientación temporal y, con frecuencia, espacial. La capacidad para resolver problemas está muy alterada.  \n 4 = Pérdida grave de memoria, conservando solamente la orientación personal. Incapacidad para elaborar juicios o resolver problemas. Requiere mucha ayuda para mantener el cuidado personal. No se puede quedar solo.','numerico','0-4',1);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (2,NULL,NULL,'2. TRASTORNOS DEL PENSAMIENTO (Por demencia o intoxicación por fármacos)','0 = No hay.  \n 1 = Ensueños vívidos.  \n 2 = Alucinaciones «benignas», conservando la capacidad de discernir. \n 3 = Alucinaciones o delirios de ocasionales a frecuentes. Sin capacidad de discernir. Pueden interferir con las actividades diarias.  \n 4 = Alucinaciones o delirios persistentes o psicosis florida. Incapaz de cuidar de sí mismo.','numerico','0-4',1);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (3,NULL,NULL,'3. DEPRESIÓN','0 = No hay. \n 1 = Períodos de tristeza o sentimientos de culpa mayores de lo normal, aunque nunca mantenidos durante días o semanas. \n 2 = Depresión mantenida (1 semana o más). \n 3 = Depresión mantenida con síntomas vegetativos (insomnio, anorexia, pérdida de peso, pérdida de interés). \n 4 = Depresión mantenida, con síntomas vegetativos y pensamientos o intento de suicidio.','numerico','0-4',1);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (4,NULL,NULL,'4. MOTIVACIÓN-INICIATIVA','0 = Normal. \n 1 = Menos pujante de lo habitual; más pasivo. \n 2 = Pérdida de iniciativa o desinterés en cuanto a actividades opcionales (no rutinarias). \n 3 = Pérdida de iniciativa o desinterés en las actividades de cada día (rutinarias). \n 4 = Aislado, apartado; pérdida total de la motivación.','numerico','0-4',1);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (5,NULL,NULL,'5. LENGUAJE','0 = Normal \n 1 = Discretamente alterado. No hay dificultad para entender \n 2 = Moderadamente alterado. A veces hay que pedirle que repita algo. \n 3 = Muy alterado. Hay que pedirle con frecuencia que repita. \n 4 = Ininteligible la mayor parte del tiempo.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (6,NULL,NULL,'6. SALIVACIÓN','0 = Normal. \n 1 = Exceso de saliva en la boca, discreto pero evidente; puede haber babeo durante la noche. \n 2 = Moderado exceso de saliva; puede haber mínimo babeo. \n 3 = Marcado exceso de saliva con cierto grado de babeo. \n 4 = Marcado babeo; requiere constantemente gasa o pañuelo.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (7,NULL,NULL,'7. DEGLUCIÓN','0 = Normal. \n 1 = Rara vez se atraganta. \n 2 = Se atraganta ocasionalmente. \n 3 = Requiere dieta blanda. \n 4 = Requiere alimentación por sonda nasogástrica o gastrostomía.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (8,NULL,NULL,'8. ESCRITURA','0 = Normal \n 1 = Discretamente lenta o pequeña. \n 2 = Moderadamente lenta o pequeña, todas las palabras son legibles.\n 3 = Muy alterada; no son legibles todas las palabras. \n 4 = La mayoría de las palabras son ilegibles.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (9,NULL,NULL,'9. CORTAR ALIMENTOS Y MANEJAR CUBIERTOS','0 = Normal. \n 1 = Algo lento y torpe, pero no necesita ayuda. \n 2 = Puede cortar la mayoría de los alimentos, aunque con torpeza y lentitud, necesita cierta ayuda. \n 3 = Le tienen que cortar los alimentos, pero aún puede alimentarse con lentitud. \n 4 = Necesita ser alimentado.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (10,NULL,NULL,'10. VESTIDO','0 = Normal. \n 1 = Algo lento, pero no requiere ayuda. \n 2 = Requiere ayuda en ocasiones para abotonarse, introducir los brazos por las mangas. \n 3 = Requiere bastante ayuda, puede hacer algunas cosas solo. \n 4 = Incapacitado.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (11,NULL,NULL,'11 HIGIENE','0 = Normal \n 1 = Algo lento, pero no necesita ayuda. \n 2 = Necesita ayuda para ducharse o bañarse, o es muy lento en las actividades higiénicas \n 3 = Requieren ayuda para lavarse, cepillarse los dientes, peinarse, ir al retrete. \n 4 = Sonda de Foley u otras ayudas mecánicas.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (12,NULL,NULL,'12 DAR VUELTAS EN CAMA Y AJUSTAR LA ROPA DE CAMA','0 = Normal. \n 1 = Algo lento y torpe, pero no precisa ayuda. \n 2 = Puede volverse solo o ajustar las sábanas, pero con gran dificultad. \n 3 = Puede iniciar la acción, pero no puede volverse o ajustar las sabanas solo. \n 4 = Incapacitado.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (13,NULL,NULL,'13. CAÍDAS (Sin relación con el fenómeno de congelación)','0 = Ninguna. \n 1 = Rara vez.\n  2 = Se cae ocasionalmente (menos de una vez al día). \n 3 = Se cae un promedio de una vez al día. \n 4 = Se cae más de una vez al día.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (14,NULL,NULL,'14. CONGELACIÓN AL CAMINAR','0 = No hay. 1 = Rara vez aparece «congelación» al caminar; puede haber titubeo al inicio. 2 = «Congelación» ocasional al caminar. 3 = «Congelación» frecuente. A veces se cae por causa de este fenómeno. 4 = Caídas frecuentes por «congelación».','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (15,NULL,NULL,'15. CAMINAR','0 = Normal. \n 1 = Leve dificultad. Puede no balancear los brazos o puede tender a arrastrar las piernas. \n 2 = Dificultad moderada, pero requiere poca o ninguna ayuda. \n 3 = Trastorno grave de la marcha que requiere ayuda. \n 4 = No puede caminar, incluso con ayuda.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (16,NULL,NULL,'16. TEMBLOR','0 = Ausente. \n 1 = Discreto; infrecuentemente presente. No resulta molesto para el paciente. \n 2 = Moderado; molesto para el paciente. \n 3 = Intenso; interfiere con muchas actividades. \n 4 = Marcado; interfiere la mayoría de las actividades.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (17,NULL,NULL,'17. SINTOMAS SENSORIALES RELACIONADOS CON EL PARKINSONISMO','0 = Normal \n 1 = Ocasionalmente tiene entumecimiento, hormigueo o dolorimiento discreto. \n 2 = Con frecuencia tiene entumecimiento, hormigueo o dolormiento discreto; no resulta penoso. \n 3 = Frecuentes sensaciones dolorosas \n 4 = Dolor extremo.','numerico','0-4',2);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (18,NULL,NULL,'18. LENGUAJE','0 = Normal. \n 1 = Pérdida discreta de expresión, dicción y/o volumen. \n 2 = Monótono; farfullado, pero comprensible; moderadamente alterado. \n 3 = Muy alterado, difícil de comprender. \n 4 = Ininteligible.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (19,NULL,NULL,'19. EXPRESIÓN FACIAL','0 = Normal. \n 1 = Mínima hipomimia; podría ser una cara inexpresiva («cara de póker») normal. \n 2 = Disminución discreta, pero claramente anormal, de la expresión facial. \n 3 = Hipomimia moderada; labios separados la mayor parte del tiempo. \n 4 = Cara «de máscara» o expresión fija con pérdida acusada o completa de la expresión facial; labios separados más de 6 mm.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (20,NULL,NULL,'20. TEMBLOR DE REPOSO EN MMSS','0 = Ausente. \n 1 = Discreto e infrecuentemente presente. \n 2 = Discreto en amplitud y persistente, o de amplitud moderada pero presente sólo de forma intermitente. \n 3 = De amplitud moderada y presente la mayor parte del tiempo. \n 4 = De gran amplitud y presente la mayor parte del tiempo.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (21,NULL,NULL,'21. TEMBLOR DE REPOSO EN MMII','0 = Ausente. \n 1 = Discreto e infrecuentemente presente. \n 2 = Discreto en amplitud y persistente, o de amplitud moderada pero presente sólo de forma intermitente. \n 3 = De amplitud moderada y presente la mayor parte del tiempo. \n 4 = De gran amplitud y presente la mayor parte del tiempo.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (22,NULL,NULL,'22. TEMBLOR DE ACCION O POSTURAL DE LAS MANOS','0 = Ausente. \n 1 = Leve; presente con la acción. \n 2 = De amplitud moderada; presente con acción. \n 3 = De amplitud moderada al mantener la postura en el aire; así como con la acción. \n 4 = De gran amplitud; interfiere la alimentación.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (23,NULL,NULL,'23. RIGIDEZ AXIAL: (Valorada según el movimiento pasivo de las grandes articulaciones, con el paciente relajado y sentado).',' 0= Ausente. \n 1 = Discreta o detectable solamente cuando se activa por movimientos en espejo o de otro tipo. \n 2 = Discreta a moderada. \n 3 = Intensa pero se consigue con facilidad el movimiento en toda su amplitud. \n 4 = Muy intensa, la amplitud del movimiento se logra con dificultad.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (24,NULL,NULL,'24. RIGIDEZ EN MMSS: (Valorada según el movimiento pasivo de las grandes articulaciones, con el paciente relajado y sentado. No considerar la rigidez «en rueda dentada»)','0 = Ausente. \n 1 = Discreta o detectable solamente cuando se activa por movimientos en espejo o de otro tipo. \n 2 = Discreta a moderada. \n 3 = Intensa, pero se consigue con facilidad el movimiento en toda su amplitud. \n 4 = Muy intensa; la amplitud del movimiento se logra con dificultad.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (25,NULL,NULL,'25.RIGIDEZ EN MMII. (Valorada según el movimiento pasivo de las grandes articulaciones, con el paciente relajado y sentado. No considerar la rigidez «en rueda dentada»)','0 = Ausente. \n 1 = Discreta o detectable solamente cuando se activa por movimientos en espejo o de otro tipo. \n 2 = Discreta a moderada. \n 3 = Intensa, pero se consigue con facilidad el movimiento en toda su amplitud. \n 4 = Muy intensa; la amplitud del movimiento se logra con dificultad.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (26,NULL,NULL,'26. GOLPETEO DE LOS DEDOS. (El paciente golpea el pulgar con el índice en rápida sucesión y con la mayor amplitud posible; realizar con cada mano por separado)','0 = Normal (15/5 segundos).\npreguntaspreguntas \n1 = Enlentecimiento discreto y/o reducción de la amplitud (11-14/5 segundos). \n2 = Moderadamente alterado. Fatigoso de manera evidente y precoz. Puede haber detenciones ocasionales en el movimiento (7-10/5 segundos). \n3 = Muy alterado. Frecuentes titubeos al iniciar los movimientos o detenciones mientras se realiza el movimiento (3-6/5 segundos). \n4 = Apenas puede realizar la acción (0-2/5 segundos).','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (27,NULL,NULL,'27. MOVIMIENTOS ALTERNANTES CON LAS MANOS (El paciente abre y cierra las manos rápida sucesión con la mayor amplitud posible)','0 = Normal. \n 1 = Discreto enlentecimiento y/o reducción de la amplitud. \n 2 = Alteración moderada. Fatigoso de manera evidente y precoz. Puede haber detenciones ocasionales en el movimiento. \n 3 = Muy alterados. Frecuentes titubeos al iniciar los movimientos o detenciones mientras se realizan los movimientos. \n 4 = Apenas puede realizarlos.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (28,NULL,NULL,'28. MOVIMIENTOS RAPIDOS ALTERNANTES DE MMSS.','0 = Normal \n 1 = Discreto enlentecimiento y/o reducción en amplitud. \n 2 = Moderadamente alterados. Fatigoso de manera evidente y precoz. Puede haber ocasionales detenciones en el movimiento. \n 3 = Muy alterados. Frecuentes titubeos al iniciar los movimientos o detenciones mientras se realizan los movimientos. \n 4 = Apenas puede realizarlos.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (29,NULL,NULL,'29. AGILIDAD CON LOS MMII. (El paciente golpea con el talón en rápida sucesión levantando el pie entero del suelo; la amplitud del movimiento debe ser alrededor de 7,5 cm.)','0 = Normal. \n 1 = Discreto enlentecimiento y/o reducción en amplitud.  \n 2 = Moderadamente alterada. Fatigosa de manera evidente y precoz. Puede haber ocasionales detenciones en el movimiento.  \n 3 = Muy alterada. Frecuentes titubeos al iniciar los movimientos o detenciones mientras se realiza el movimiento.  \n  4 = Apenas puede realizar la acción.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (30,NULL,NULL,'30. LEVANTARSE DE LA SILLA. (El paciente intenta levantarse de una silla de madera o metal de respaldo recto, con los brazos cruzados ante el pecho)','0 = Normal. \n 1 = Lento, o puede necesitar más de un intento. \n 2 = Tiene que impulsarse con los brazos en la silla. \n 3 = Tiende a caer hacia atrás y puede tener que intentarlo más de una vez, pero puede conseguirlo sin ayuda. \n 4 = Incapaz de levantarse sin ayuda.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (31,NULL,NULL,'31. POSTURA','0 = Erecta normal. \n 1 = Postura no muy erecta, discretamente encorvada; podía ser normal en una persona mayor. \n 2 = Postura moderadamente encorvada, claramente anormal. Puede inclinarse discretamente a un lado \n  3 = Postura muy encorvada, con cifosis. Puede inclinarse moderadamente a un lado. \n  4 = Flexión marcada con alteración postural extrema.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (32,NULL,NULL,'32. MARCHA','0 = Normal. \n 1 = Camina lentamente; pueden arrastrar los pies, con paso cortos, pero sin festinación ni propulsión. \n 2 = Camina con dificultad, pero no requiere ayuda o muy escasa. Puede haber festinación, pasos cortos o propulsionados. \n 3 = Trastornos graves de la marcha que requieren ayuda. \n 4 = No puede caminar, incluso con ayuda.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (33,NULL,NULL,'33. ESTABILIDAD POSTURAL. (respuesta al desplazamiento súbito posterior producido por un tirón de los hombros mientras el paciente permanece en bipedestación con los ojos abiertos y los pies discretamente separados; el paciente esta avisado)','0 = Normal. \n 1 = Retropulsión, pero se recupera sin ayuda. \n 2 = Ausencia de respuesta postural; se cacería si no le sujetara el examinador. \n 3 = Muy inestable; tiende a perder el equilibrio espontáneamente. \n 4 = Incapaz de permanecer en pie sin ayuda.','numerico','0-4',3);
INSERT INTO `preguntas` (`id`,`created_at`,`updated_at`,`titulo`,`enunciado`,`tiporespuesta`,`rango`,`formulario_id`) VALUES (34,NULL,NULL,'34. BRADIQUINESA E HIPOQUINESIA.(Combina lentitud, titubeo, disminución del braceo, pequeña amplitud y pobreza de movimiento, en general).','0 = No hay. \n 1 = Mínima lentitud que da al movimiento un carácter deliberado; podría ser normal en algunas personas. Amplitud posiblemente reducida. \n 2 = Lentitud y pobreza de movimientos, en grado leve, que es claramente anormal. Como alternativa, cierto grado de reducción en la amplitud. \n 3 = Lentitud, pobreza o pequeña amplitud de movimientos moderada. \n 4 = Lentitud, pobreza o pequeña amplitud de movimientos marcada.','numerico','0-4',3);
