/*
-- Query: SELECT * FROM homestead.tratamientos
LIMIT 0, 1000

-- Date: 2020-05-19 23:20
*/
INSERT INTO `tratamientos` (`id`,`dosis`,`frecuencia`,`fechainicio`,`fechafin`,`detalles`,`paciente_id`,`medicamento_id`) VALUES (1,600,2,'2018-01-01','2019-01-01','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tellus turpis, quis tempus est blandit sit amet. Vestibulum arcu urna, sodales sed felis at, gravida sagittis dolor. Etiam magna nibh, pharetra id maximus nec, dignissim ac odio. Proin sem dui, vulputate nec tincidunt quis, laoreet sit amet orci. Vivamus quis rhoncus mauris, sit amet venenatis est. In vel pharetra eros. Curabitur hendrerit ante dui, sed consectetur purus malesuada eu. Sed dignissim enim et imperdiet consequat. Morbi tempus in libero id aliquam.',1,2);
INSERT INTO `tratamientos` (`id`,`dosis`,`frecuencia`,`fechainicio`,`fechafin`,`detalles`,`paciente_id`,`medicamento_id`) VALUES (2,500,3,'2019-01-01','2019-01-01','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tellus turpis, quis tempus est blandit sit amet. Vestibulum arcu urna, sodales sed felis at, gravida sagittis dolor. Etiam magna nibh, pharetra id maximus nec, dignissim ac odio. Proin sem dui, vulputate nec tincidunt quis, laoreet sit amet orci. Vivamus quis rhoncus mauris, sit amet venenatis est. In vel pharetra eros. Curabitur hendrerit ante dui, sed consectetur purus malesuada eu. Sed dignissim enim et imperdiet consequat. Morbi tempus in libero id aliquam.',1,4);
INSERT INTO `tratamientos` (`id`,`dosis`,`frecuencia`,`fechainicio`,`fechafin`,`detalles`,`paciente_id`,`medicamento_id`) VALUES (3,400,4,'2019-01-01','2025-01-01','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus tellus turpis, quis tempus est blandit sit amet. Vestibulum arcu urna, sodales sed felis at, gravida sagittis dolor. Etiam magna nibh, pharetra id maximus nec, dignissim ac odio. Proin sem dui, vulputate nec tincidunt quis, laoreet sit amet orci. Vivamus quis rhoncus mauris, sit amet venenatis est. In vel pharetra eros. Curabitur hendrerit ante dui, sed consectetur purus malesuada eu. Sed dignissim enim et imperdiet consequat. Morbi tempus in libero id aliquam.',1,3);
